[project]
name = "smolagents-quickstart-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "langchain-community>=0.3.30",
    "loguru>=0.7.3",
    "openai<1.100.0",
    "chromadb>=0.5.20",
    "smolagents[gradio,litellm,mcp,telemetry,toolkit]>=1.21.1",
    "pytest>=8.3",
    "flask>=3.1.2",
    "utils>=1.0.2",
    "tiktoken>=0.8.0",
    "dotenv>=0.9.9",
    "sentence-transformers>=5.1.2",
]
